import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, AlertTriangle, Info } from "lucide-react";
import SEOPageWrapper from "~/components/templates/SEOPageWrapper";

const BASE_URL = "https://www.humanifylab.com";
const URL = `${BASE_URL}/ai-detector`;

export const metadata: Metadata = {
  title: { absolute: "AI Detector: How AI Detectors Work & How to Pass Every One | HumanifyLab" },
  description: "What is an AI detector, how do Turnitin, GPTZero and Originality.AI actually work, and how accurate are they really? Full 2026 breakdown plus how to pass every one.",
  keywords: ["ai detector", "ai detectors", "what is an ai detector", "how do ai detectors work", "best ai detector", "ai detector accuracy", "bypass ai detector"],
  authors: [{ name: "HumanifyLab", url: BASE_URL }],
  alternates: { canonical: URL },
  openGraph: {
    title: "AI Detector: How AI Detectors Work & How to Pass Every One",
    description: "A full breakdown of how AI detectors work, how accurate they really are, and how to make your writing pass every one.",
    url: URL,
    siteName: "HumanifyLab",
    type: "article",
    images: [{ url: `${BASE_URL}/forOpenGraph.png`, width: 1200, height: 630, alt: "AI Detector Guide — HumanifyLab" }],
  },
  twitter: {
    card: "summary_large_image",
    title: "AI Detector: How AI Detectors Work & How to Pass Every One",
    description: "How AI detectors work, how accurate they are, and how to pass every one.",
    images: [`${BASE_URL}/forOpenGraph.png`],
  },
  robots: { index: true, follow: true, googleBot: { index: true, follow: true, "max-video-preview": -1, "max-image-preview": "large", "max-snippet": -1 } },
};

const DETECTOR_COMPARISON = [
  { name: "Turnitin", type: "Academic", falsePositive: "Estimated 1-4% on human writing", notes: "Most widely deployed in higher education; flags are visible to instructors as a percentage." },
  { name: "GPTZero", type: "Academic + General", falsePositive: "Estimated 2-5%", notes: "Popular with individual educators; combines perplexity and burstiness scoring." },
  { name: "Originality.AI", type: "Publishing / SEO", falsePositive: "Estimated 3-6%", notes: "Common among content agencies checking freelance and AI-assisted work." },
  { name: "ZeroGPT", type: "General", falsePositive: "Estimated 2-5%", notes: "Free-to-use, widely embedded in browser tools and Chrome extensions." },
  { name: "Copyleaks", type: "Enterprise / LMS", falsePositive: "Estimated 1-4%", notes: "Deeply integrated into Canvas, Blackboard and Moodle for institutional use." },
];

const FAQS = [
  { q: "What exactly is an AI detector?", a: "An AI detector is software that estimates the probability that a piece of text was generated by an AI language model rather than written by a human. It does this by analyzing statistical patterns in the text — not by 'knowing' anything about how the text was actually produced." },
  { q: "How accurate are AI detectors?", a: "Independent testing consistently shows AI detectors produce false positives on human-written text at rates of roughly 1-6%, and their accuracy on AI text drops significantly once that text has been lightly edited or paraphrased. No major detector claims, or achieves, 100% accuracy in either direction." },
  { q: "Can AI detectors be wrong about human-written text?", a: "Yes, this is one of the most documented weaknesses of AI detection. Formal, structured, or non-native-English writing is disproportionately flagged as AI-generated even when written entirely by a human, because these detectors key on predictability and structural regularity, not authorship." },
  { q: "Which AI detector is the most accurate?", a: "There is no universally 'most accurate' detector — different tools optimize for different tradeoffs between false positives and false negatives, and accuracy varies by content type, subject, and language. This is why institutions and companies increasingly layer multiple detectors rather than relying on one." },
  { q: "How do I make sure my writing passes AI detection?", a: "The most reliable approach is to rewrite AI-drafted text so the underlying statistical signature — word predictability, sentence length variation, and structural rhythm — matches natural human writing, which is exactly what HumanifyLab does. Simple synonym-swapping or light editing usually is not enough on its own." },
];

export default function AiDetectorPage() {
  const jsonLd = {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "Article",
        "@id": `${URL}#article`,
        headline: "AI Detector: How AI Detectors Work & How to Pass Every One",
        description: "A complete breakdown of how AI detectors work, how accurate they are, and how to pass every major one.",
        inLanguage: "en-US",
        author: { "@type": "Organization", name: "HumanifyLab", url: BASE_URL },
        publisher: {
          "@type": "Organization", name: "HumanifyLab", url: BASE_URL,
          logo: { "@type": "ImageObject", url: `${BASE_URL}/humanify.png`, width: 512, height: 512 },
        },
        mainEntityOfPage: { "@type": "WebPage", "@id": URL },
      },
      {
        "@type": "FAQPage",
        "@id": `${URL}#faq`,
        mainEntity: FAQS.map((f) => ({ "@type": "Question", name: f.q, acceptedAnswer: { "@type": "Answer", text: f.a } })),
      },
      {
        "@type": "BreadcrumbList",
        "@id": `${URL}#breadcrumb`,
        itemListElement: [
          { "@type": "ListItem", position: 1, name: "Home", item: BASE_URL },
          { "@type": "ListItem", position: 2, name: "AI Detectors", item: `${BASE_URL}/topics/detector` },
          { "@type": "ListItem", position: 3, name: "AI Detector", item: URL },
        ],
      },
    ],
  };

  return (
    <SEOPageWrapper keyword="ai detector" cluster="detector" publishDate="2026-01-15" updatedDate="2026-06-20" readTime={8}>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
      <div className="min-h-screen bg-white">
        <section className="bg-[#0f1419] text-white py-16 px-4">
          <div className="max-w-4xl mx-auto text-center">
            <span className="inline-flex items-center gap-2 text-xs font-semibold uppercase tracking-widest text-[#8b6f47] mb-4">
              <Info className="w-4 h-4" /> Complete 2026 Breakdown
            </span>
            <h1 className="text-3xl sm:text-4xl lg:text-5xl font-extrabold mb-4 leading-tight">
              AI Detector: How They Work, How Accurate They Are, and How to Pass Every One
            </h1>
            <p className="text-gray-400 text-base sm:text-lg max-w-2xl mx-auto mb-8">
              An AI detector doesn't read your text for meaning — it scores statistical patterns. Here's exactly
              what that means, which detectors matter most, where they get it wrong, and how HumanifyLab makes
              your writing pass every one of them.
            </p>
            <Link href="/bypass-ai-detectors" className="inline-flex items-center gap-2 bg-[#8b6f47] hover:bg-[#7a6040] text-white font-semibold px-8 py-4 rounded-xl transition-colors text-sm">
              See the Bypass Guide <ArrowRight className="w-4 h-4" />
            </Link>
          </div>
        </section>

        <section className="py-16 px-4 bg-white">
          <div className="max-w-3xl mx-auto">
            <h2 className="text-2xl font-bold text-gray-900 mb-6">What Is an AI Detector?</h2>
            <p className="text-gray-600 leading-relaxed mb-4">
              An AI detector is a piece of software — usually a fine-tuned classifier model — trained to estimate
              the probability that a given piece of text was produced by a large language model like GPT-4, Claude,
              or Gemini rather than written by a human. It outputs a score (often shown as a percentage) representing
              that probability, not a factual determination.
            </p>
            <p className="text-gray-600 leading-relaxed mb-4">
              To do this, detectors look at signals such as <strong>perplexity</strong> (how predictable each word
              is given the preceding context — AI text tends to choose the statistically "safest" next word more
              often than humans do), <strong>burstiness</strong> (the natural variation in sentence length and
              structure that human writing has and AI writing often lacks), and increasingly, structural and
              semantic patterns learned by training the classifier on large datasets of known AI and human text.
            </p>
            <p className="text-gray-600 leading-relaxed">
              Because detectors are pattern-matching systems rather than authorship-verification tools, they are
              fundamentally probabilistic — which is why every major detector below carries a documented error rate
              in both directions.
            </p>
          </div>
        </section>

        <section className="py-16 px-4 bg-gray-50">
          <div className="max-w-5xl mx-auto">
            <h2 className="text-2xl font-bold text-gray-900 text-center mb-4">Major AI Detectors Compared</h2>
            <p className="text-gray-600 text-center max-w-2xl mx-auto mb-10 text-sm">
              False-positive figures below are drawn from independently published testing and HumanifyLab's own
              ongoing verification; treat them as informed estimates rather than guaranteed rates, since every
              detector updates its model periodically.
            </p>
            <div className="overflow-x-auto rounded-2xl border border-gray-200 shadow-sm bg-white">
              <table className="w-full text-sm">
                <thead>
                  <tr className="bg-[#0f1419] text-white">
                    <th className="text-left px-6 py-4 font-semibold">Detector</th>
                    <th className="text-left px-6 py-4 font-semibold">Primary Use</th>
                    <th className="text-left px-6 py-4 font-semibold">Est. False Positive Rate</th>
                    <th className="text-left px-6 py-4 font-semibold">Notes</th>
                  </tr>
                </thead>
                <tbody>
                  {DETECTOR_COMPARISON.map((d, i) => (
                    <tr key={d.name} className={i % 2 === 0 ? "bg-white" : "bg-gray-50"}>
                      <td className="px-6 py-4 font-medium text-gray-800">{d.name}</td>
                      <td className="px-6 py-4 text-gray-500">{d.type}</td>
                      <td className="px-6 py-4 text-[#5e3d2a] font-medium">{d.falsePositive}</td>
                      <td className="px-6 py-4 text-gray-500">{d.notes}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </section>

        <section className="py-16 px-4 bg-white">
          <div className="max-w-3xl mx-auto">
            <div className="bg-amber-50 border border-amber-200 rounded-xl p-6 flex gap-4">
              <AlertTriangle className="w-6 h-6 text-amber-600 flex-shrink-0 mt-0.5" />
              <div>
                <h3 className="font-semibold text-gray-900 mb-1">AI detectors flag real human writing too</h3>
                <p className="text-sm text-gray-700 leading-relaxed">
                  Formal academic writing, non-native English phrasing, and even highly structured business writing
                  get flagged as "AI-generated" at meaningful rates across every detector in the table above. If
                  you're a human writer who has been incorrectly flagged, HumanifyLab can also help — see our{" "}
                  <Link href="/how-to-fix-ai-flagged-my-essay" className="text-[#8b6f47] hover:underline">guide to fixing a false AI flag</Link>.
                </p>
              </div>
            </div>
          </div>
        </section>

        <section className="py-16 px-4 bg-gray-50">
          <div className="max-w-3xl mx-auto">
            <h2 className="text-2xl font-bold text-gray-900 text-center mb-8">Frequently Asked Questions</h2>
            <div className="space-y-4">
              {FAQS.map((faq) => (
                <div key={faq.q} className="bg-white rounded-xl border border-gray-200 p-6">
                  <h3 className="font-semibold text-gray-900 mb-2">{faq.q}</h3>
                  <p className="text-gray-600 text-sm leading-relaxed">{faq.a}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        <section className="py-16 px-4 bg-[#0f1419] text-white text-center">
          <div className="max-w-2xl mx-auto">
            <h2 className="text-2xl font-bold mb-3">Ready to Pass Every AI Detector?</h2>
            <p className="text-gray-400 mb-6">99.9% bypass rate, verified weekly. Free plan, no sign-up required.</p>
            <Link href="/" className="inline-flex items-center gap-2 bg-[#8b6f47] hover:bg-[#7a6040] text-white font-semibold px-8 py-4 rounded-xl transition-colors">
              Try HumanifyLab Free <ArrowRight className="w-4 h-4" />
            </Link>
          </div>
        </section>
      </div>
    </SEOPageWrapper>
  );
}
