/**
 * FULL uniqueness + indexability audit across ALL 41,810 pSEO pages (v1–v5 + geo).
 *
 * Checks:
 *   1.  Slug uniqueness — zero duplicates across all datasets
 *   2.  Metadata uniqueness — duplicate meta titles and descriptions
 *   3.  H1 uniqueness — duplicate H1 headings
 *   4.  Content fingerprint (first FAQ question+answer) — deep content similarity
 *   5.  Internal link resolution — every href generated by buildRelatedLinks
 *        resolves to a real page (no 404s)
 *   6.  Canonical slug validity — no slug empty, too short (<5), too long (>120),
 *        or containing characters that would break URL encoding
 *   7.  Meta title/description length SERPs compliance
 *   8.  JSON-LD fields present on every page (via content generators)
 *
 * Run: npx tsx scripts/full-uniqueness-audit.ts
 */

import { getAllSlugs, getClusterKeywords } from "../src/lib/pseo-data";
import { getAllV2Slugs, getV2ClusterKeywords } from "../src/lib/pseo-data-v2";
import { getAllV3Slugs, getV3ClusterKeywords } from "../src/lib/pseo-data-v3";
import { getAllV4Slugs, getV4ClusterKeywords } from "../src/lib/pseo-data-v4";
import { getAllV5Entries } from "../src/lib/pseo-data-v5";
import { getAllGeoSlugs, getGeoClusterKeywords } from "../src/lib/pseo-data-geo";
import { buildRelatedLinks } from "../src/lib/related-links";

import { generateBypassContent } from "../src/lib/content/bypass-content";
import { generateHumanizerContent } from "../src/lib/content/humanizer-content";
import { generateHowToContent } from "../src/lib/content/howto-content";
import { generateUseCaseContent } from "../src/lib/content/usecase-content";
import { generateCompetitorContent } from "../src/lib/content/competitor-content";
import { generateAcademicContent } from "../src/lib/content/academic-content";
import { generateProfessionalContent } from "../src/lib/content/professional-content";
import { generateDetectorContent } from "../src/lib/content/detector-content";
import { generateLanguageContent } from "../src/lib/content/language-content";
import { generateNicheContent } from "../src/lib/content/niche-content";
import { generatePricingContent } from "../src/lib/content/pricing-content";
import { generateIndustryContent } from "../src/lib/content/industry-content";
import { generateFormatContent } from "../src/lib/content/format-content";
import { generateSpeedContent } from "../src/lib/content/speed-content";
import { generateQualityContent } from "../src/lib/content/quality-content";
import { generateToolContent } from "../src/lib/content/tool-content";
import { generateProblemContent } from "../src/lib/content/problem-content";
import { generateWorkflowContent } from "../src/lib/content/workflow-content";
import { generateScoreContent } from "../src/lib/content/score-content";
import { generateRegionContent } from "../src/lib/content/region-content";
import { generateComparisonContent } from "../src/lib/content/comparison-content";
import { generateAlternativeContent } from "../src/lib/content/alternative-content";
import { generateReviewContent } from "../src/lib/content/review-content";
import { generateFreeContent } from "../src/lib/content/free-content";
import { generateDetectionContent } from "../src/lib/content/detection-content";
import { generateWritingContent } from "../src/lib/content/writing-content";
import { generateEducationContent } from "../src/lib/content/education-content";
import { generatePlatformV4Content } from "../src/lib/content/platform-content-v4";
import { generateOutputContent } from "../src/lib/content/output-content";
import { generateBulkContent } from "../src/lib/content/bulk-content";
import { generateGeoContent } from "../src/lib/content/geo-content";
import { generateCityContent } from "../src/lib/content/city-content";
import { generateQuestionContent } from "../src/lib/content/question-content";
import { generateFeatureContent } from "../src/lib/content/feature-content";
import { generateLengthContent } from "../src/lib/content/length-content";
import { generateScenarioContent } from "../src/lib/content/scenario-content";

const t0 = Date.now();

// ── Static routes that are valid link targets but not pSEO pages ─────────────
const VALID_NON_PSEO = new Set([
  "/", "/pricing", "/faq", "/contact", "/responsible-use", "/terms", "/privacy",
  "/bypass-ai-detectors", "/ai-detector", "/topics",
]);

// ── Aggregate all entries from every dataset ─────────────────────────────────
type AnyEntry = { slug: string; keyword: string; cluster: string; entity: string; seed: number };

const allEntries: AnyEntry[] = [];

// V1
for (const c of ["bypass","humanizer","howto","usecase"] as const) {
  for (const e of getClusterKeywords(c)) allEntries.push({ ...e, cluster: c });
}
// V2
for (const c of ["competitor","academic","professional","detector","language","niche"] as const) {
  for (const e of getV2ClusterKeywords(c)) allEntries.push({ ...e, cluster: c });
}
// V3
for (const c of ["pricing","industry","format","speed","quality","tool","problem","workflow","score","region"] as const) {
  for (const e of getV3ClusterKeywords(c)) allEntries.push({ ...e, cluster: c });
}
// V4
for (const c of ["comparison","alternative","review","free","detection","writing","education","platform","output","bulk"] as const) {
  for (const e of getV4ClusterKeywords(c)) allEntries.push({ ...e, cluster: c });
}
// V5
for (const e of getAllV5Entries()) allEntries.push({ ...e });
// Geo
for (const e of getGeoClusterKeywords()) allEntries.push({ ...e, cluster: "geo" });

console.log(`total entries assembled: ${allEntries.length}`);

// ── CHECK 1: Slug uniqueness ──────────────────────────────────────────────────
const slugSeen = new Map<string, string>(); // slug -> cluster
let slugDupes = 0;
for (const e of allEntries) {
  if (slugSeen.has(e.slug)) {
    slugDupes++;
    if (slugDupes <= 5) console.log(`  SLUG DUPE: "${e.slug}" in ${slugSeen.get(e.slug)} AND ${e.cluster}`);
  } else {
    slugSeen.set(e.slug, e.cluster);
  }
}
console.log(`\n[1] Slug uniqueness: ${slugDupes} duplicates (expect 0)`);

// ── CHECK 2–4: Metadata + H1 + content fingerprint uniqueness ────────────────
// Generate content for EVERY entry (this exercises every content generator)
const titleMap = new Map<string, number>();
const descMap = new Map<string, number>();
const h1Map = new Map<string, number>();
const fingerprintMap = new Map<string, number>();

let genErrors = 0;
let missingFaqs = 0;
let emptyTitles = 0, emptyDescs = 0, emptyH1s = 0;

// Map cluster -> generator function
function getGenerator(entry: AnyEntry): ((e: AnyEntry) => { metaTitle: string; metaDescription: string; h1: string; faqs: { q: string; a: string }[] }) | null {
  switch (entry.cluster) {
    case "bypass": return (e) => generateBypassContent(e as any);
    case "humanizer": return (e) => generateHumanizerContent(e as any);
    case "howto": return (e) => generateHowToContent(e as any);
    case "usecase": return (e) => generateUseCaseContent(e as any);
    case "competitor": return (e) => generateCompetitorContent(e as any);
    case "academic": return (e) => generateAcademicContent(e as any);
    case "professional": return (e) => generateProfessionalContent(e as any);
    case "detector": return (e) => generateDetectorContent(e as any);
    case "language": return (e) => generateLanguageContent(e as any);
    case "niche": return (e) => generateNicheContent(e as any);
    case "pricing": return (e) => generatePricingContent(e as any);
    case "industry": return (e) => generateIndustryContent(e as any);
    case "format": return (e) => generateFormatContent(e as any);
    case "speed": return (e) => generateSpeedContent(e as any);
    case "quality": return (e) => generateQualityContent(e as any);
    case "tool": return (e) => generateToolContent(e as any);
    case "problem": return (e) => generateProblemContent(e as any);
    case "workflow": return (e) => generateWorkflowContent(e as any);
    case "score": return (e) => generateScoreContent(e as any);
    case "region": return (e) => generateRegionContent(e as any);
    case "comparison": return (e) => generateComparisonContent(e as any);
    case "alternative": return (e) => generateAlternativeContent(e as any);
    case "review": return (e) => generateReviewContent(e as any);
    case "free": return (e) => generateFreeContent(e as any);
    case "detection": return (e) => generateDetectionContent(e as any);
    case "writing": return (e) => generateWritingContent(e as any);
    case "education": return (e) => generateEducationContent(e as any);
    case "platform": return (e) => generatePlatformV4Content(e as any);
    case "output": return (e) => generateOutputContent(e as any);
    case "bulk": return (e) => generateBulkContent(e as any);
    case "geo": return (e) => generateGeoContent(e as any);
    case "city": return (e) => generateCityContent(e as any);
    case "question": return (e) => generateQuestionContent(e as any);
    case "feature": return (e) => generateFeatureContent(e as any);
    case "length": return (e) => generateLengthContent(e as any);
    case "scenario": return (e) => generateScenarioContent(e as any);
    default: return null;
  }
}

for (const entry of allEntries) {
  const gen = getGenerator(entry);
  if (!gen) { genErrors++; continue; }
  let data: { metaTitle: string; metaDescription: string; h1: string; faqs: { q: string; a: string }[] };
  try { data = gen(entry); } catch (err) { genErrors++; continue; }

  if (!data.metaTitle) emptyTitles++;
  if (!data.metaDescription) emptyDescs++;
  if (!data.h1) emptyH1s++;
  if (!data.faqs || data.faqs.length === 0) missingFaqs++;

  titleMap.set(data.metaTitle, (titleMap.get(data.metaTitle) ?? 0) + 1);
  descMap.set(data.metaDescription, (descMap.get(data.metaDescription) ?? 0) + 1);
  h1Map.set(data.h1, (h1Map.get(data.h1) ?? 0) + 1);

  // Content fingerprint: first FAQ question (unique per-entry signal)
  const fq = data.faqs?.[0]?.q ?? "";
  fingerprintMap.set(fq, (fingerprintMap.get(fq) ?? 0) + 1);
}

const dupTitles = [...titleMap.entries()].filter(([, n]) => n > 1);
const dupDescs = [...descMap.entries()].filter(([, n]) => n > 1);
const dupH1s = [...h1Map.entries()].filter(([, n]) => n > 1);
const dupFingerprints = [...fingerprintMap.entries()].filter(([, n]) => n > 1);

const dupTitlePageCount = dupTitles.reduce((s, [, n]) => s + n, 0);
const dupDescPageCount = dupDescs.reduce((s, [, n]) => s + n, 0);
const dupH1PageCount = dupH1s.reduce((s, [, n]) => s + n, 0);
const dupFingerprintCount = dupFingerprints.reduce((s, [, n]) => s + n, 0);

console.log(`\n[2] Meta title uniqueness:`);
console.log(`    ${dupTitles.length} duplicate titles covering ${dupTitlePageCount} pages (${((dupTitlePageCount / allEntries.length) * 100).toFixed(2)}%)`);
if (dupTitles.length > 0) {
  for (const [t, n] of dupTitles.sort((a,b) => b[1]-a[1]).slice(0, 5)) console.log(`    x${n}: ${t}`);
}
console.log(`    Empty titles: ${emptyTitles}`);

console.log(`\n[3] Meta description uniqueness:`);
console.log(`    ${dupDescs.length} duplicate descriptions covering ${dupDescPageCount} pages (${((dupDescPageCount / allEntries.length) * 100).toFixed(2)}%)`);
if (dupDescs.length > 0) {
  for (const [d, n] of dupDescs.sort((a,b) => b[1]-a[1]).slice(0, 3)) console.log(`    x${n}: ${d.slice(0, 100)}...`);
}
console.log(`    Empty descriptions: ${emptyDescs}`);

console.log(`\n[4] H1 uniqueness:`);
console.log(`    ${dupH1s.length} duplicate H1s covering ${dupH1PageCount} pages (${((dupH1PageCount / allEntries.length) * 100).toFixed(2)}%)`);
if (dupH1s.length > 0) {
  for (const [h, n] of dupH1s.sort((a,b) => b[1]-a[1]).slice(0, 5)) console.log(`    x${n}: ${h}`);
}
console.log(`    Empty H1s: ${emptyH1s}`);

console.log(`\n[4b] Content fingerprint (first FAQ question):`);
console.log(`     ${dupFingerprints.length} duplicate fingerprints covering ${dupFingerprintCount} pages (${((dupFingerprintCount / allEntries.length) * 100).toFixed(2)}%)`);
if (dupFingerprints.length > 0) {
  for (const [f, n] of dupFingerprints.sort((a,b) => b[1]-a[1]).slice(0, 3)) console.log(`     x${n}: ${f.slice(0, 100)}`);
}

// ── CHECK 5: Internal link 404 resolution (every entry) ──────────────────────
const allSlugsSet = new Set(allEntries.map((e) => e.slug));
function isValidHref(href: string): boolean {
  if (VALID_NON_PSEO.has(href)) return true;
  if (href.startsWith("/topics/")) return true; // cluster hub pages
  return allSlugsSet.has(href.replace(/^\//, ""));
}

let linkChecked = 0;
let linkBroken = 0;
const brokenByCluster = new Map<string, number>();
const brokenExamples: string[] = [];

// Check EVERY entry (not sampled — we want 100% coverage)
for (const entry of allEntries) {
  for (const link of buildRelatedLinks(entry.cluster, entry.keyword)) {
    linkChecked++;
    if (!isValidHref(link.href)) {
      linkBroken++;
      brokenByCluster.set(entry.cluster, (brokenByCluster.get(entry.cluster) ?? 0) + 1);
      if (brokenExamples.length < 10) brokenExamples.push(`${entry.slug}  ->  ${link.href} ("${link.label}")`);
    }
  }
}

console.log(`\n[5] Internal link 404 check (${allEntries.length} pages × ~8 links each):`);
console.log(`    Checked: ${linkChecked}   Broken: ${linkBroken}`);
if (linkBroken > 0) {
  console.log(`    By cluster:`);
  for (const [c, n] of [...brokenByCluster.entries()].sort((a,b) => b[1]-a[1])) {
    console.log(`      ${c.padEnd(12)} ${n} broken links`);
  }
  console.log(`    Examples:`);
  for (const b of brokenExamples) console.log(`      ${b}`);
}

// ── CHECK 6: Slug validity ────────────────────────────────────────────────────
let slugTooShort = 0, slugTooLong = 0, slugBadChars = 0;
const badSlugExamples: string[] = [];
const SLUG_VALID = /^[a-z0-9-]+$/;
for (const e of allEntries) {
  let bad = false;
  if (e.slug.length < 5) { slugTooShort++; bad = true; }
  if (e.slug.length > 120) { slugTooLong++; bad = true; }
  if (!SLUG_VALID.test(e.slug)) { slugBadChars++; bad = true; }
  if (bad && badSlugExamples.length < 5) badSlugExamples.push(e.slug);
}

console.log(`\n[6] Slug validity:`);
console.log(`    Too short (<5):   ${slugTooShort}`);
console.log(`    Too long (>120):  ${slugTooLong}`);
console.log(`    Bad chars:        ${slugBadChars}`);
if (badSlugExamples.length > 0) for (const s of badSlugExamples) console.log(`    BAD: "${s}"`);

// ── CHECK 7: Title / description length compliance ────────────────────────────
let tooLongTitle = 0, tooShortTitle = 0, tooLongDesc = 0, tooShortDesc = 0;
for (const [t, n] of titleMap) {
  if (t.length > 65) tooLongTitle += n;
  if (t.length < 25) tooShortTitle += n;
}
for (const [d, n] of descMap) {
  if (d.length > 170) tooLongDesc += n;
  if (d.length < 70) tooShortDesc += n;
}
console.log(`\n[7] SERP length compliance:`);
console.log(`    Titles >65 chars:  ${tooLongTitle} (${((tooLongTitle/allEntries.length)*100).toFixed(1)}%) — truncated in SERPs, not an error`);
console.log(`    Titles <25 chars:  ${tooShortTitle}`);
console.log(`    Descs >170 chars:  ${tooLongDesc} (${((tooLongDesc/allEntries.length)*100).toFixed(1)}%) — truncated in SERPs, not an error`);
console.log(`    Descs <70 chars:   ${tooShortDesc}`);

// ── CHECK 8: Generation errors ───────────────────────────────────────────────
console.log(`\n[8] Generation errors: ${genErrors}   Missing FAQs: ${missingFaqs}`);

// ── SUMMARY ───────────────────────────────────────────────────────────────────
console.log(`\n═══════════════════════════════════════════════════════`);
console.log(`TOTAL PAGES: ${allEntries.length}`);
const hardFailures = slugDupes + genErrors + linkBroken + slugTooShort + slugTooLong + slugBadChars + emptyTitles + emptyDescs + emptyH1s + missingFaqs;
const warnOnlyIssues = dupTitles.length + dupDescs.length + dupH1s.length + tooLongTitle + tooShortTitle + tooLongDesc;
console.log(`HARD FAILURES (must fix before deploy): ${hardFailures}`);
console.log(`WARNINGS (SERP-quality, not blocking):  ${warnOnlyIssues > 0 ? dupTitles.length + ' dup titles, ' + dupDescs.length + ' dup descs, ' + tooLongTitle + ' long titles' : 'none'}`);
console.log(`done in ${Date.now() - t0}ms`);

if (hardFailures > 0) process.exit(1);
